import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :snap, SnapWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json",
  check_origin: ["//localhost", "//snap.dinosur.app"],
  url: [host: "https://snap.dinosur.app"],
  http: [port: 4000, compress: true],
  secret_key_base: "mYsDMNjmYuRwEABp0REreeh+F9Y0BWOsPzzYNHV3POye+a6BwSl/4UF9jaMcih3X",
  server: true

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: Snap.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.

config :snap, Snap.Repo,
  # username: "postgres",
  # password: "postgres",
  # hostname: "localhost",
  # database: "snap_dev",
  # stacktrace: true,
  # show_sensitive_data_on_connection_error: true,
  # pool_size: 10

  # dinosur
  username: "postgres",
  password: "Ruda,actv1",
  hostname: "167.235.150.40",
  database: "snap_dev",
  port: 5432,
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10
